# Generated by Django 4.0.3 on 2022-03-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('viewer_hour', models.PositiveIntegerField()),
                ('hours_streamed', models.PositiveIntegerField()),
                ('acv_num', models.PositiveIntegerField()),
                ('creators', models.PositiveIntegerField()),
                ('streams_num', models.PositiveIntegerField()),
            ],
        ),
    ]
